name: Build

on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: build application
        run: make

      - name: upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: virtualjaguar_libretro.*
          if-no-files-found: error

      - name: download artifacts
      - uses: actions/download-artifact@v2
        with:
          name: results

      # - name: comment PR
      #   uses: machine-learning-apps/pr-comment@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     path: results/results.txt